import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 30,
    paddingVertical: 50,
  },
  conteudo: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: {
    width: 120,
    height: 120,
    marginBottom: 20,
    resizeMode: 'contain',
  },
  titulo: {
    fontFamily: 'Gill Sans',
    fontSize: 26,
    fontWeight: 'bold',
    color: '#1A1A1A',
    marginBottom: 10,
    textAlign: 'center',
  },
  subtitulo: {
    fontFamily: 'Gill Sans',
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 40,
    lineHeight: 22,
  },
  campoInput: {
    fontFamily: 'Gill Sans',
    width: '100%',
    height: 55,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    paddingHorizontal: 15,
    marginBottom: 15,
    fontSize: 16,
    backgroundColor: '#F9F9F9',
    color: '#333',
  },
  botaoEntrar: {
    backgroundColor: '#2D6A4F',
    width: '100%',
    height: 55,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    elevation: 2,
  },
  textoBotaoEntrar: {
    fontFamily: 'Gill Sans',
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  botaoCadastrar: {
    backgroundColor: '#FFFFFF',
    width: '100%',
    height: 55,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#2D6A4F',
  },
  textoBotaoCadastrar: {
    fontFamily: 'Gill Sans',
    color: '#2D6A4F',
    fontWeight: 'bold',
    fontSize: 16,
  },
  divisor: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 30,
    width: '100%',
  },
  linha: {
    flex: 1,
    height: 1,
    backgroundColor: '#EEEEEE',
  },
  textoDivisor: {
    fontFamily: 'Gill Sans',
    marginHorizontal: 15,
    color: '#999',
    fontSize: 14,
  },
  botaoVisitante: {
    marginTop: 30,
    padding: 10,
  },
  textoBotaoVisitante: {
    fontFamily: 'Gill Sans',
    color: '#2D6A4F',
    fontWeight: '600',
    fontSize: 15,
    textDecorationLine: 'underline',
  }
});